import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/headers/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const res = await fetch("https://api.binance.com/api/v3/ticker/price");
  if (!res.ok) {
    throw new Error("Network response was not ok");
  }
  const data = await res.json();
  const prices = data.reduce((acc, pair) => {
    // Bitcoin, Ethereum, Solana, Cardano, Terra, Polkadot
    if (
      pair.symbol === "BTCUSDT" ||
      pair.symbol === "ETHUSDT" ||
      pair.symbol === "SOLUSDT" ||
      pair.symbol === "ADAUSDT" ||
      pair.symbol === "LUNAUSDT" ||
      pair.symbol === "DOTUSDT"
    ) {
      // round off to 2 decimal places
      acc[pair.symbol] = Math.round(pair.price * 100) / 100;
    }
    return acc;
  }, {});

  return prices;
}

export default async function RootLayout({ children }) {
  const data = await getData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header prices={data} />
        {children}
      </body>
    </html>
  );
}
